#spring.profiles.active=sqlserver
spring.profiles.active=mysql
spring.config.import=optional:application-local.properties
jwt.expiration=43200000
paypal.client-id=AbmysnbLGLU6VbeC4XPSpPOhxZ4ITh0DMOwhWDMdS54farre2EGHRsxswr_3R9ujfBiStBzgsrIP7qO5
paypal.base-url=https://api-m.sandbox.paypal.com
